name: base
channels:
  - conda-forge
#  - pkgs/main
dependencies:
  - conda
  - h5py
  - hdf5
  - defaults::intel-openmp
  - blas=*=mkl  # so blas is replaced by mkl, needed in Miniconda3-py37_22.11.1-1-Linux-x86_64.sh and forward
  - defaults::mkl
  - defaults::numpy
  - packaging  # needed to compare version strings
  - pandas
  - pango  # needed by weasyprint
  - pip
  - python=3.12
  - pip:
    - itk
    - jinja2  # to generate html reports
    - jsonschema  # to enabled json schema input validation
    - matplotlib
    - nibabel
    - nvitop
    - portalocker
    - pydicom
    - weasyprint  # to convert the html reports to pdf
    - xmltodict
    - parmap
    - scipy
    - scikit-image
    - scikit-learn
    - simpleitk
    - watchdog
