name: base
channels:
  - defaults
dependencies:
  - conda
  - h5py
  - hdf5
  - intel-openmp
  - blas=*=mkl  # so blas is replaced by mkl, needed in Miniconda3-py37_22.11.1-1-Linux-x86_64.sh and forward
  - mkl=2023.1.0
  - numpy=1.25.2  # pinned to make np.__config__.lapack_mkl_info keep working (not working in 1.26.0, AttributeError: module 'numpy.__config__' has no attribute 'lapack_mkl_info')
  - packaging  # needed to compare version strings
  - pandas
  - pango  # needed by weasyprint
  - pip
  - python=3.11
  - pip:
    - defusedxml  # needed by openpyxl to generate Excel Sheet
    - dicom-anonymizer  # needed to anonymize dicom input files
    - itk
    - jinja2  # to generate html reports
    - jsonschema  # to enabled json schema input validation
    - matplotlib
    - mysql-connector-python
    - nibabel
    - nvitop
    - openpyxl  # needed for pandas to generated Excel Sheet
    - paramiko
    - portalocker
    - pydicom
    - pysftp
    - weasyprint  # to convert the html reports to pdf
    - xmltodict
    - pdfrw
    - parmap
    - scipy
    - scikit-image
    - scikit-learn
    - simpleitk
